version: "3.8"
services:

  postgres:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      volumes: "./postgres:/var/lib/postgresql/data"
    networks:
      - golang

  go:
    container_name: api
    image: ilhamfzz/dockerize-golang-altera
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    networks:
      - golang

networks:
  golang:
    driver: bridge